# Generated by Django 2.2.7 on 2019-11-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('contact', models.ManyToManyField(related_name='contact_list', to='mattest.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
